[options]
word-separators = -A-Za-z0-9,./?%&#:_=+@~
buffer-lines = 2000
startup-local = True
log-local = False
confirm-exit = True
font-color = 
back-color = 
term = 
transparency = 0
paste-right-click = True
confirm-close-tab = False
confirm-close-tab-middle = True
check-updates = True
font = Monospace 9
donate = True
auto-copy-selection = False
log-path = /home/endavis/logs
version = 1
auto-close-tab = 0
cycle-tabs = True
update-title = False
app-title = Gnome Connection Manager

[window]
collapsed-folders = 
left-panel-width = 456
window-width = -1
window-height = -1
show-panel = True
show-toolbar = True

[host 1]
group = AWS
name = bastproxy
description = 
host = bp.endavis.net
user = endavis
pass = ttqYitJnvghNGcK6WL0BkO6rRAydNU+HG3LrdYZyEIE=
private_key = 
port = 22
tunnel = 
type = ssh
commands = 
keepalive = 0
font-color = 
back-color = 
x11 = True
agent = True
compression = False
compression-level = 0
extra_params = 
log = True
backspace-key = 0
delete-key = 0
term = 

[host 2]
group = AWS
name = bastproxy (ubuntu)
description = bp.endavis.net
host = bp.endavis.net
user = ubuntu
pass = pnL6XUK8f3YO+Q/b4IAxlGCxo13m54WrOkW73Lx9iUw=
private_key = 
port = 22
tunnel = 
type = ssh
commands = 
keepalive = 0
font-color = 
back-color = 
x11 = True
agent = True
compression = False
compression-level = 0
extra_params = 
log = True
backspace-key = 0
delete-key = 0
term = 

[host 3]
group = AWS
name = bp
description = 
host = bp.endavis.net
user = 
pass = JotvELodRbbk5B5H+nG1RZt+mQPTwLEwlLS1Ujyd1V0=
private_key = 
port = 9999
tunnel = 
type = telnet
commands = 
keepalive = 0
font-color = 
back-color = 
x11 = False
agent = False
compression = False
compression-level = 0
extra_params = 
log = True
backspace-key = 0
delete-key = 0
term = 

[host 4]
group = BastProxy/Local
name = BP Clean
description = 
host = 
user = 
pass = 7KsR/uAGlhyUJS+r0k/aN0S2lzSuPZxuKvZIyaqqVc0=
private_key = 
port = 23
tunnel = 
type = local
commands = tmuxp load ~/.config/tmux/bastproxy-clean.tmuxp.yaml -y
keepalive = 0
font-color = 
back-color = 
x11 = False
agent = False
compression = False
compression-level = 0
extra_params = 
log = True
backspace-key = 0
delete-key = 0
term = 

[host 5]
group = BastProxy/Local
name = BP Local
description = 
host = 
user = 
pass = Pf4uf28XY2geVoH3IBLS7z85vRR/jnRsNAs9SJH8vyY=
private_key = 
port = 23
tunnel = 
type = local
commands = tmuxp load ~/.config/tmux/bastproxy.tmuxp.yaml -y
keepalive = 0
font-color = 
back-color = 
x11 = False
agent = False
compression = False
compression-level = 0
extra_params = 
log = True
backspace-key = 0
delete-key = 0
term = 

[host 6]
group = BastProxy/AWS
name = BP AWS
description = 
host = bp.endavis.net
user = endavis
pass = cdhwWhUmr/UBr1uR3gmQJvN+LgQ18MWWezdTghSUusA=
private_key = 
port = 22
tunnel = 
type = ssh
commands = tmuxp load ~/.config/tmux/bastproxy.tmuxp.yaml -y
keepalive = 120
font-color = 
back-color = 
x11 = True
agent = True
compression = False
compression-level = 0
extra_params = 
log = True
backspace-key = 0
delete-key = 0
term = 

[shortcuts]
copy = CTRL+SHIFT+C
paste = CTRL+SHIFT+V
copy_all = CTRL+SHIFT+A
save = CTRL+S
find = CTRL+F
find_next = CTRL+G
find_back = CTRL+H
console_previous = CTRL+SHIFT+TAB
console_next = CTRL+TAB
console_close = CTRL+W
console_reconnect = CTRL+N
connect = CTRL+RETURN
reset = CTRL+SHIFT+K
clone = CTRL+SHIFT+D
new_local = CTRL+SHIFT+N
console_1 = ALT+1
console_2 = ALT+2
console_3 = ALT+3
console_4 = ALT+4
console_5 = ALT+5
console_6 = ALT+6
console_7 = ALT+7
console_8 = ALT+8
console_9 = ALT+9

